source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Random' do
    pod 'AlamofireImage'
    pod 'SnapKit', '~> 4.0.1'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Moya/RxSwift'
end

target 'RandomTests' do
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
